services:
  discord-telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-telegram-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - BOT_TOKEN=${BOT_TOKEN}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./.env:/app/.env # Mount the local .env file into the container
    depends_on:
      - redis

  deploy-commands:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-telegram-deploy-commands
    environment:
      - NODE_ENV=production
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
    command: node ./dist/deploy-commands.js
    profiles:
      - commands

  redis:
    image: redis:alpine
    container_name: discord-telegram-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  redis-data: